// TypesFromSerializers CacheKey b8af6beb071f45e87fe53318043f5388
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ComposerWithSongsSong {
  id: number
  title?: string
}
