// TypesFromSerializers CacheKey a69c0dbcc904740e5de89181ef4b2837
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ComposerWithSongsSong {
  id: number
  title?: string
}
