/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InertiaLink: typeof import('./components/InertiaLink.vue')['default']
    Link: typeof import('./components/Link.vue')['default']
    PageList: typeof import('./components/PageList.vue')['default']
    PageSubtitle: typeof import('./components/PageSubtitle.vue')['default']
    PageTitle: typeof import('./components/PageTitle.vue')['default']
    TheNavBar: typeof import('./components/TheNavBar.vue')['default']
    YouTubePlayer: typeof import('./components/YouTubePlayer.vue')['default']
  }
}
