// TypesFromSerializers CacheKey 1d3cc3a892b5b124a7f3f2fbe959233a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AnyModel from '~/types/AnyModel'

export default interface Model {
  id: AnyModel['id']
  title: AnyModel['title']
}
