// TypesFromSerializers CacheKey c5f5056c4fa3626c5c1908d0f1dcfe8d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Composer {
  id: number
  firstName?: string
  lastName?: string
  name: string
}
