// TypesFromSerializers CacheKey 3aa811bd4673913bbd09f2967979b304
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Composer from './Composer'
import type Video from './Video'

export default interface SongWithVideos {
  id: number
  composer: Composer
  genre: "disco" | "rock" | "classical"
  tempo: "slow" | "medium" | "fast"
  title?: string
  videos: Video[]
}
