// TypesFromSerializers CacheKey 460b4a83a2e81c9d693ac5490f9e0b76
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Composer from './Composer'

export default interface Song {
  id: number
  composer: Composer
  genre: "disco" | "rock" | "classical"
  tempo: "slow" | "medium" | "fast"
  title?: string
}
