// TypesFromSerializers CacheKey 9111c6d881174b0013582fa6366868db
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ComposerWithSongsSong from './ComposerWithSongs/Song'

export default interface ComposerWithSongs {
  id: number
  firstName?: string
  lastName?: string
  name: string
  songs: ComposerWithSongsSong[]
}
