// TypesFromSerializers CacheKey d0a8343adcd13dd1da6ea8a62133a958
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Composer {
  id: number
  firstName?: string
  lastName?: string
  name: string
}
