// TypesFromSerializers CacheKey ddc921e1e92a90ea686336285fcdb369
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AnyModel from '../../AnyModel'
import type Song from '../Song'

export default interface NestedAlbum {
  id: AnyModel['id']
  title: AnyModel['title']
  tracks: Song[]
}
