// TypesFromSerializers CacheKey 45d6b515fb6118eabbd39d586269cdd0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Video {
  id: number
  createdAt: string | Date
  title?: string
  untypedFieldExample: any
  youtubeId?: string
  youtubeUrl?: string
}
