// TypesFromSerializers CacheKey d5b0a2f49cfe468b27fefa6611f3be22
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Composer from '~/types/serializers/Composer'
import type Video from '~/types/serializers/Video'

export default interface SongWithVideos {
  id: number
  title?: string
  composer: Composer
  videos: Video[]
}
