// TypesFromSerializers CacheKey 63a5894ee4bee3376a2288598f754c8c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Video {
  id: number
  createdAt: string | Date
  title?: string
  youtubeId?: string
  youtubeUrl: string
}
