// TypesFromSerializers CacheKey ca72d9955fb1b71ba747af06c3c5d891
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Song from '~/types/serializers/Song'

export default interface VideoWithSong {
  id: number
  createdAt: string | Date
  title?: string
  youtubeId?: string
  youtubeUrl?: string
  song: Song
}
