// TypesFromSerializers CacheKey 324ddf780cc56438c072bb4d40e1b7e7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Song from '~/types/serializers/Song'

export default interface VideoWithSong {
  id: number
  createdAt: string | Date
  title?: string
  youtubeId?: string
  youtubeUrl?: string
  untypedFieldExample: any
  song: Song
}
