// TypesFromSerializers CacheKey ac8c8ed6ef3e8b487290522c6759ad34
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Video {
  id: number
  createdAt: string | Date
  title?: string
  youtubeId?: string
  youtubeUrl?: string
}
