// TypesFromSerializers CacheKey c60fdecd73955e093e975794215bee01
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Composer from '~/types/serializers/Composer'

export default interface Song {
  id: number
  title?: string
  composer: Composer
}
