// TypesFromSerializers CacheKey ed8ff6fbc986e6b666d559749c666dc5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AnyModel from '../AnyModel'

export default interface Model {
  id: AnyModel['id']
  title: AnyModel['title']
}
