// TypesFromSerializers CacheKey acbbfcd258be7c495d2784be9b815e79
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ComposerWithSongsSong from './ComposerWithSongs/Song'

export default interface ComposerWithSongs {
  id: number
  firstName?: string
  lastName?: string
  name: string
  songs: ComposerWithSongsSong[]
}
