// TypesFromSerializers CacheKey 418c6496db7a4463e18bfecbab03cc1e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Model from '~/types/serializers/Model'

export default interface ComposerWithSongs {
  id: number
  firstName?: string
  lastName?: string
  name: string
  songs: Model[]
}
