// TypesFromSerializers CacheKey 89c74246c39a38f244b708597ef3b884
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AnyModel from '../AnyModel'

export default interface Model {
  id: AnyModel['id']
  title: AnyModel['title']
}
