// TypesFromSerializers CacheKey 0dbfd6f12887ff9569aafbe9cbe3183d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Model {
  id: number
  title: string
}
