// TypesFromSerializers CacheKey 03a6c67042bb201dfeeab4b021db7dd5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface SnakeComposer {
  id: number
  first_name?: string
  last_name?: string
  name: string
}
