// TypesFromSerializers CacheKey ab7d8a50fcb2a2aab051ea483906c8c4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Composer from '~/types/serializers/Composer'
import type VideoClip from '~/types/serializers/VideoClip'

export default interface SongWithVideos {
  id: number
  title?: string
  composer: Composer
  videos: VideoClip[]
}
