// TypesFromSerializers CacheKey c2c60f7c58d2fbafd49219bd8673dd15
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Composer from './Composer'

export default interface Song {
  id: number
  composer: Composer
  genre: "fingerstyle" | "rock" | "classical"
  tempo: "slow" | "medium" | "fast"
  title?: string
}
