// TypesFromSerializers CacheKey 8b7c143fd23d866177b843924ae4ba46
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface VideoClip {
  id: number
  title?: string
  youtubeId?: string
  youtubeUrl: string
}
