// TypesFromSerializers CacheKey 8665f1ca69e0682ab94ba8402a06e438
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Song from '~/types/serializers/Song'

export default interface VideoWithSong {
  id: number
  createdAt: string | Date
  title?: string
  youtubeId?: string
  youtubeUrl: string
  song: Song
}
