// TypesFromSerializers CacheKey 39cef93f8b1171cc3ff8f0d3e17d9c7a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Song from '~/types/serializers/Song'

export default interface VideoClipWithSong {
  id: number
  title?: string
  youtubeId?: string
  youtubeUrl: string
  song: Song
}
