// TypesFromSerializers CacheKey 45f0743cbff26512b711824dbd700573
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Video {
  id: number
  createdAt: string | Date
  title?: string
  youtubeId?: string
  youtubeUrl?: string
  untypedFieldExample: any
}
