// TypesFromSerializers CacheKey fa77137240a406b724863f5d51e9c3e4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Video {
  id: number
  createdAt: string | Date
  title?: string
  untypedFieldExample: any
  /**
  * YouTube ID of the video
  */
  youtubeId?: string
  youtubeUrl?: string
}
