// TypesFromSerializers CacheKey 1eadebf7ba2bd6b7f531b228527d7d2d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Song from '~/types/serializers/Song'

export default interface VideoWithSong {
  id: number
  title?: string
  youtubeId?: string
  youtubeUrl: string
  song: Song
}
