// JsFromRoutes CacheKey 5d0e017a4589ba07dd01a67b2f32ddaa
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as composers } from '~/api/ComposersApi'
export { default as songs } from '~/api/SongsApi'
export { default as videos } from '~/api/VideosApi'
