// JsFromRoutes CacheKey 657f5e8dc19e6058650cf9bba2b0ef3d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: definePathHelper('get', '/composers'),
  show: definePathHelper('get', '/composers/:id'),
}
