// JsFromRoutes CacheKey 3c504c24ef7fee1ff1bf10bc1f5939b4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: definePathHelper('get', '/songs'),
  show: definePathHelper('get', '/songs/:id'),
}
