// JsFromRoutes CacheKey 460b3f8cfdc3c7b11c64fb451b5063a8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: definePathHelper('get', '/videos'),
  show: definePathHelper('get', '/videos/:id'),
}
