dylan_ryche = Composer.create!(first_name: "Dylan", last_name: "Ryche")
maximo_mussini = Composer.create!(first_name: "Máximo", last_name: "Mussini")
leon_gieco = Composer.create!(first_name: "León", last_name: "Gieco")
calum_graham = Composer.create!(first_name: "Calum", last_name: "Graham")
matteo_brenci = Composer.create!(first_name: "Matteo", last_name: "Brenci")
michael_hedges = Composer.create!(first_name: "Michael", last_name: "Hedges")
antonio_lauro = Composer.create!(first_name: "Antonio", last_name: "Lauro")
celso_machado = Composer.create!(first_name: "Celso", last_name: "Machado")
astor_piazzolla = Composer.create!(first_name: "Astor", last_name: "Piazzolla")
jorge_cardoso = Composer.create!(first_name: "Jorge", last_name: "Cardoso")
domingos_semenzato = Composer.create!(first_name: "Domingos", last_name: "Semenzato")

smoke_signals = Song.create(title: "Smoke Signals", composer: dylan_ryche)
camino_libre = Song.create(title: "Camino Libre", composer: maximo_mussini)
sin_querer = Song.create(title: "Sin Querer", composer: leon_gieco)
tabula_rasa = Song.create(title: "Tabula Rasa", composer: calum_graham)
raindance = Song.create(title: "Raindance", composer: matteo_brenci)
ragamuffin = Song.create(title: "Ragamuffin", composer: michael_hedges)
vals_venezolano_n_2 = Song.create(title: "Vals Venezolano Nº 2", composer: antonio_lauro)
xaranga_do_vovo = Song.create(title: "Xaranga do Vovô", composer: celso_machado)
cafe_1930 = Song.create(title: "Café 1930", composer: astor_piazzolla)
milonga_uruguay = Song.create(title: "Milonga (Uruguay)", composer: jorge_cardoso)
divagando = Song.create(title: "Divagando", composer: domingos_semenzato)

VideoClip.create!(id: 11, song: smoke_signals, youtube_id: "3glhadBFKGc", title: "Máximo Mussini interpreta \"Smoke Signals\" por Dylan Ryche")
VideoClip.create!(id: 10, song: camino_libre, youtube_id: "7cUCxXuBk_8", title: "\"Camino Libre\" by Máximo Mussini")
VideoClip.create!(id: 9, song: sin_querer, youtube_id: "birhb9Ozmws", title: "Máximo Mussini plays \"Sin Querer\" by León Gieco")
VideoClip.create!(id: 8, song: tabula_rasa, youtube_id: "AE00vTJQ7z4", title: "Máximo Mussini plays \"Tabula Rasa\" by Calum Graham")
VideoClip.create!(id: 7, song: raindance, youtube_id: "UbeLr5dwwtI", title: "Máximo Mussini plays \"Raindance\" by Matteo Brenci")
VideoClip.create!(id: 6, song: ragamuffin, youtube_id: "Yf8pSlJimIc", title: "Máximo Mussini plays \"Ragamuffin\" by Michael Hedges")
VideoClip.create!(id: 5, song: vals_venezolano_n_2, youtube_id: "Qa-dX-iFrRg", title: "Máximo Mussini plays \"Vals Venezolano Nº 2\" by Antonio Lauro")
VideoClip.create!(id: 4, song: xaranga_do_vovo, youtube_id: "p-932nEHYko", title: "Máximo Mussini plays \"Xaranga do Vovô\" by Celso Machado")
VideoClip.create!(id: 3, song: cafe_1930, youtube_id: "gT6rDZVPPWo", title: "Máximo Mussini plays \"Café 1930 (Intro)\" by Astor Piazzolla")
VideoClip.create!(id: 2, song: milonga_uruguay, youtube_id: "fUguoMhv7fs", title: "Máximo Mussini plays \"Milonga (Uruguay)\" by Jorge Cardoso")
VideoClip.create!(id: 1, song: divagando, youtube_id: "_iAT3nXfpT0", title: "Máximo Mussini plays \"Divagando (Choro)\" by Domingos Semenzato")
