name: tsc

on: [push]

jobs:
  tsc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.6
          run_install: |
            - recursive: false

      - name: Clean Types
        run: pnpm clean

      - name: Generate Types
        run: pnpm gen

      - name: Type Check
        run: pnpm tsc
